baseURL = "https://www.jinhduong.com"
languageCode = "en-us"
title = "jinhduong's blog - you keep the sunshine, save me the rain"
theme = "dinify"

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
    [[menu.main]]
        identifier = "en"
        name = "eng posts"
        url = "/en"
    [[menu.main]]
        identifier = "til"
        name = "tils"
        url = "/til"
    # [[menu.main]]
    #     identifier = "archives"
    #     name = "archives"
    #     url = "/archives"
    # [[menu.main]]
    #     identifier = "good blogs"
    #     name = "good blogs"
    #     url = "/good-blogs"

[params]
  github = "https://github.com/jinhduong"
  twitter = "https://twitter.com/jinhduong"
  email = "0961020@gmail.com"
  quotes = true

[taxonomies]
   tag = "tags"
   category = "categories"

